# Generated by Django 5.2.8 on 2025-11-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('engine_temp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pressure_fuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('altitude_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('velocity_kmh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attitude_roll', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'telemetry_data',
            },
        ),
    ]
